### ISSUE TITLE
nnUNetv2_predict: not found

### ISSUE THREAD

**Issue by lzw269** [TaoZhong11/TIPs#1]
Processing Teeth Segmentation.
sh: 1: nnUNetv2_predict: not found
Generating Prior Maps.
Automatic centroid calculation selected.
Processing Teeth Instance Segmentation.
sh: 1: nnUNetv2_predict: not found
Renumber the instance
请问这个要怎么处理

**Comment by TaoZhong11** [comment]
您好，这应该是nnUNet没install成功？可以参照Installation部分。

**Comment by lzw269** [comment]
您好，请问又报nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
应该是这些路径没找到：
nnUNet_raw = os.environ.get('nnUNet_raw')
nnUNet_preprocessed = os.environ.get('nnUNet_preprocessed')
nnUNet_results = os.environ.get('nnUNet_results')
请问该怎么处理

**Comment by TaoZhong11** [comment]
vi ~/.bashrc
export nnUNet_raw = "/home/path/to/TIPs/nnUNet_raw"  # raw_data_path
export nnUNet_preprocessed = "/home/path/to/TIPs/nnUNet_preprocessed"  # preprocessed_data_path
export nnUNet_results = "/home/path/to/TIPs/nnResults"  # models_path
source ~/.bashrc

**Comment by lzw269** [comment]
不配置nnUNet_raw和nnUNet_preprocessed也能跑通
