### ISSUE TITLE
分割结果不是很准确

### ISSUE THREAD

**Issue by yuyichuan** [TaoZhong11/TIPs#3]
我试了一下， 发现分割时候， 牙位会分割不准确，比如如把一个牙分成了两个牙（各缺一部分）， 推测可能是训练样本是不是不够丰富， 所以，  您能提供训练部分的代码吗？
![Uploading 20241025112155.jpg…]()

**Comment by TaoZhong11** [comment]
The training code and data will be made available following the acceptance of the paper. Thank you!
